version: '3'

services:
  nodejs_wmw:
    container_name: nodejs_wmw
    build: ./node
    volumes:
      - ./node:/usr/src/test
    ports:
      - "55420:55420"
    environment:
      - NODE_EVN=development

  nginx_wmw:
    container_name: nginx_wmw
    image: nginx_wmw
    volumes:
    - ./templates:/etc/nginx/templates
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./conf.d:/etc/nginx/conf.d
    - ./html:/usr/share/nginx/html
    ports:
    - "55555:80"
    environment:
    - NGINX_PORT=80