version: '3'

services:
  nodejs_wmw:
    container_name: nodejs_wmw
    build: ./node
    volumes:
      - ./node:/usr/src/test
    ports:
      - "55420:55420"
      - "55421:55421"
    environment:
      - NODE_EVN=development